### PR TITLE
ADX-407 Debug access string (requires Jinja2==2.11)

### PR DESCRIPTION
**Pull request by jonathansberry**

### CODE REVIEW

**Review by tomeksabala — CHANGES_REQUESTED** [review]
Looks alright. You should add an entry to requirmenets.txt with new jinja2 version.

**Comment by jonathansberry** [comment]
Builds are breaking due to "No matching version setup tools can be found."  No point in trying to fix travis builds at this time of day when it takes 20 minutes to queue each job. Will come back to it tomorrow.

**Comment by jonathansberry** [comment]
Related PRS: 
https://github.com/fjelltopp/adx_develop/pull/16
https://github.com/fjelltopp/adx_deploy/pull/50

**Review by tomeksabala — APPROVED** [review]
LGTM

**Pull request merged**
